# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d809d0e7ca41694604b9df7f467e03384f4e7ecfc977d4db75cb4199386125f58be9e131371a0d6ff54bf030b17e64b6fcce72b0e0942e733fb3228b4c31e553

test:
  secret_key_base: aaf6b3c26736b375b1e8ba0919920165cecb6f49124e003629a0f00b0db0c2524d2cc085893142b693309cbbc5819771fa5ebedac2ed30583f288b38a6eb051c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
